name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          eslint_flags: '.'
